spring.application.name=apiMonkey

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
spring.liquibase.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Developer tools
spring.devtools.add-properties=true
spring.thymeleaf.cache=false

# Logging
logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n

# Auth
spring.security.oauth2.client.registration.google.client-id=861951343727-tqtb8gt05rbpghpn5ihka5p2anbgfip5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=TT7QAloufNkl_5cJBLntMFJm

# Mail Server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apiautomation9@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true