
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Flyway Configuration for H2
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Logging
logging.level.org.flywaydb=DEBUG

# Mail Server (Mock/Default)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apiautomation9@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Auth
spring.security.oauth2.client.registration.google.client-id=861951343727-tqtb8gt05rbpghpn5ihka5p2anbgfip5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=TT7QAloufNkl_5cJBLntMFJm
