CREATE TABLE `swagger_data` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NULL,
  `PAGE_CONTENT` TEXT NULL,
  `CREATED_DATE` DATETIME NULL,
  `UPDATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`));

CREATE INDEX `URL_INDEX` ON `swagger_data` (`URL` ASC);
CREATE INDEX `UPDATED_DATE_INDEX` ON `swagger_data` (`UPDATED_DATE` ASC);

ALTER TABLE `swagger_data`
ADD COLUMN `HASH_ID` VARCHAR(255) NULL AFTER `URL`;

ALTER TABLE `swagger_data`
ADD COLUMN `PASSED_URL` VARCHAR(500) NULL DEFAULT NULL AFTER `URL`;

