CREATE TABLE `user_data_case` (
  `ID` INT(11) NOT NULL,
  `DATA_ID` VARCHAR(255) NULL,
  `DATA_NAME` VARCHAR(255) NULL,
  `SWAGGER_DATA_ID` INT(11) NULL,
  `USER_ID` INT(11) NULL,
  `DATA_CASE_CONTENT` LONGTEXT NULL,
  `UPDATED_DATE` DATETIME NULL,
  `CREATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `user_data_case`
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;
