ALTER TABLE `user` ADD COLUMN `PROVIDER` VARCHAR(95) NOT NULL AFTER `TYPE`;
ALTER TABLE `user` ADD COLUMN `PROVIDER_ID` VARCHAR(255) NULL DEFAULT NULL AFTER `PROVIDER`;
ALTER TABLE `user` ADD COLUMN `IMAGE_URL` VARCHAR(255) NULL DEFAULT NULL AFTER `PROVIDER_ID`;
ALTER TABLE `user` ADD COLUMN `EMAIL_VERIFIED` TINYINT(1) NULL DEFAULT 0 AFTER `IMAGE_URL`;
ALTER TABLE `user` CHANGE COLUMN `LOGIN` `LOGIN` VARCHAR(255) NOT NULL;
ALTER TABLE `user` CHANGE COLUMN `TYPE` `TYPE` VARCHAR(45) NOT NULL;
