CREATE TABLE `swagger_data` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NULL,
  `PAGE_CONTENT` TEXT NULL,
  `CREATED_DATE` DATETIME NULL,
  `UPDATED_DATE` DATETIME NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE `swagger_data`
ADD INDEX `URL_INDEX` (`URL` ASC),
ADD INDEX `UPDATED_DATE_INDEX` (`UPDATED_DATE` ASC);

ALTER TABLE `swagger_data`
ADD COLUMN `HASH_ID` VARCHAR(255) NULL AFTER `URL`;
