CREATE TABLE `error_messages_log` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NULL DEFAULT NULL,
  `USER_LOGIN` VARCHAR(255) NULL DEFAULT NULL,
  `ERROR_MESSAGE` TEXT NULL DEFAULT NULL,
  `STACK_TRACE` LONGTEXT NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
