ALTER TABLE `user` ADD COLUMN `FIRST_NAME` VARCHAR(255) NULL DEFAULT NULL AFTER `PASSWORD`;
ALTER TABLE `user` ADD COLUMN `LAST_NAME` VARCHAR(255) NULL DEFAULT NULL AFTER `FIRST_NAME`;
ALTER TABLE `user` ADD COLUMN `CREATED` DATETIME NULL DEFAULT NULL AFTER `TYPE`;
ALTER TABLE `user` CHANGE COLUMN `LOGIN` `LOGIN` VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE `user` CHANGE COLUMN `PASSWORD` `PASSWORD` VARCHAR(255) NULL DEFAULT NULL;

DROP TABLE IF EXISTS `persistent_logins`;
CREATE TABLE `persistent_logins` (
  `USERNAME` varchar(255) not null,
  `SERIES` varchar(64) primary key,
  `TOKEN` varchar(64) not null,
  `LAST_USED` timestamp not null
);