ALTER TABLE `user`
ADD COLUMN `PROVIDER` VARCHAR(95) NOT NULL AFTER `TYPE`,
ADD COLUMN `PROVIDER_ID` VARCHAR(255) NULL DEFAULT NULL AFTER `PROVIDER`,
ADD COLUMN `IMAGE_URL` VARCHAR(255) NULL DEFAULT NULL AFTER `PROVIDER_ID`,
ADD COLUMN `EMAIL_VERIFIED` TINYINT(1) NULL DEFAULT 0 AFTER `IMAGE_URL`,
CHANGE COLUMN `LOGIN` `LOGIN` VARCHAR(255) NOT NULL,
CHANGE COLUMN `TYPE` `TYPE` VARCHAR(45) NOT NULL ;
